/**
 * products.js - Database sản phẩm chi tiết
 */

export const PRODUCTS_DB = {
  "h1": {
    id: "h1",
    name: "Organic Bananas",
    unit: "7pcs, Price",
    price: 4.99,
    description: "Bananas are an excellent source of potassium, vitamin B6, and vitamin C. They are rich in antioxidants and may help reduce blood sugar levels after meals. Bananas are also great for heart health and digestion.",
    image: require("@/assets/images/banana.png"),
    nutrition: "100g",
    rating: 5,
  },
  "h3": {
    id: "h3",
    name: "Ớt Chuông",
    unit: "1kg, Price",
    price: 4.99,
    description: "Bell peppers are high in vitamin C and antioxidants. They support eye health, reduce inflammation, and may help lower cholesterol. Available in multiple colors including red, yellow, and green varieties.",
    image: require("@/assets/images/otchuong.png"),
    nutrition: "100g",
    rating: 5,
  },
  "h4": {
    id: "h4",
    name: "Rau Xanh",
    unit: "1kg, Price",
    price: 2.99,
    description: "Fresh green vegetables packed with essential nutrients and vitamins. Rich in fiber, minerals, and antioxidants. Perfect for salads, cooking, and maintaining a healthy diet for your family.",
    image: require("@/assets/images/rau.png"),
    nutrition: "100g",
    rating: 5,
  },
  "h7": {
    id: "h7",
    name: "Beef Bone",
    unit: "500g, Price",
    price: 4.99,
    description: "Premium beef bone cuts perfect for making nutritious bone broth or stews. High in collagen, calcium, and minerals that support joint and bone health. Fresh and best quality from trusted sources.",
    image: require("@/assets/images/thitbo.png"),
    nutrition: "100g",
    rating: 5,
  },
  "h8": {
    id: "h8",
    name: "Broiler Chicken",
    unit: "1kg, Price",
    price: 4.99,
    description: "Fresh and tender broiler chicken ideal for grilling, frying, or cooking in any style. Rich in protein and low in fat, making it perfect for a healthy and balanced diet. Farm-fresh quality guaranteed.",
    image: require("@/assets/images/thitga.png"),
    nutrition: "100g",
    rating: 5,
  },
  "h2": {
    id: "h2",
    name: "Naturel Red Apple",
    unit: "1kg, Price",
    price: 4.99,
    description: "Apples are nutritious. Apples may be good for weight loss. Apples may be good for your heart. As part of a healthful and varied diet.",
    image: require("@/assets/images/apple.png"),
    nutrition: "100g",
    rating: 5,
  },
  "b1": {
    id: "b1",
    name: "Diet Coke",
    unit: "355ml, Price",
    price: 1.99,
    description: "The classic sugar-free cola you know and love. Zero calories, zero sugar, and all the taste you need for a refreshing break.",
    image: require("@/assets/images/diet-coke.png"),
    nutrition: "355ml",
    rating: 5,
  },
  "b2": {
    id: "b2",
    name: "Sprite Can",
    unit: "325ml, Price",
    price: 1.50,
    description: "Crisp, refreshing lemon-lime soda. Perfectly balanced sweetness and carbonation to quench your thirst.",
    image: require("@/assets/images/sprite-can.png"),
    nutrition: "325ml",
    rating: 5,
  },
  "b3": {
    id: "b3",
    name: "Apple & Grape Juice",
    unit: "2L, Price",
    price: 15.99,
    description: "A delicious blend of sweet apples and tart grapes. 100% juice with no added sugar, perfect for the whole family.",
    image: require("@/assets/images/apple-and-grape-juice.png"),
    nutrition: "250ml",
    rating: 5,
  },
  "b4": {
    id: "b4",
    name: "Orange Juice",
    unit: "2L, Price",
    price: 15.99,
    description: "Freshly squeezed orange juice packed with Vitamin C. No pulp, no preservatives, just pure citrus goodness.",
    image: require("@/assets/images/orange-juice.png"),
    nutrition: "250ml",
    rating: 5,
  },
  "b5": {
    id: "b5",
    name: "Coca Cola Can",
    unit: "325ml, Price",
    price: 4.99,
    description: "The original cola taste. Refreshing, bubbly, and perfect with any meal.",
    image: require("@/assets/images/cocacola.png"),
    nutrition: "325ml",
    rating: 5,
  },
  "b6": {
    id: "b6",
    name: "Pepsi Can",
    unit: "330ml, Price",
    price: 4.99,
    description: "Bold, refreshing Pepsi cola. Great taste that's globally loved.",
    image: require("@/assets/images/pepsi.png"),
    nutrition: "330ml",
    rating: 5,
  },
};

export const getProductById = (id) => {
  return PRODUCTS_DB[id] || PRODUCTS_DB["h2"];
};
